### ISSUE TITLE
Test if installed application running

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#1]
Hello,
I'm very happy that you did't stop work on Packages.
I have a small improvement proposal.
Some installers can detect running applications and if running application(s) is(are) detected show warning and wait to close that apps. I'd like to see that option in Packages.
For best description of problem, please see included screenshot from Skype4Business installer.
![mustclosedapp](https://cloud.githubusercontent.com/assets/5236788/24296157/2e97041c-109e-11e7-99e3-c5f643403414.png)

**Comment by packagesdev** [comment]
I would need to look into this after the 1.2 release. It's not clear from the Apple's documentation which minimum version of (M|m)ac ?OS( X)? supports this.

**Comment by ferben** [comment]
Software requirements for this version of Skype for Business is OSX 10.11 (El Capitan) or OSX 10.12 (Sierra)

**Comment by rudyrichter** [comment]
sorry for hijacking the thread but, @ferben do you work on the installer for Skype for Business? could you possibly update the `mkdir -p ~/Library/Application Support/Google/Chrome/NativeMessagingHost` script so that it creates the directory as the user instead of the installer (which causes it to be owned by root)?

**Comment by ferben** [comment]
Fortunatelly no – I'm not Microsoft employee. The screenshot is only example of feature which I'd like to see in Packages.app

**Comment by packagesdev** [comment]
This will be supported in version 1.2.2.

**Comment by packagesdev** [comment]
Supported in 1.2.2 (315)
