### ISSUE TITLE
Unable to copy item at path <path>

### ISSUE THREAD

**Issue by misku** [packagesdev/packages#10]
Hello,
I've just upgraded Packages to 1.2 (211). Thank you for uploading the source on gitub. Kudos!

**The issue I'm encountering is:**
```
ERROR:

Description:

Unable to copy item at path '/tmp/script.sh'
```
while trying to build the project.

**When does it happen:**
When at least two packages on the "Installation Type" list are using a requirement "Result of an external script" and the script used is the same for both packages.

**How to recreate:**
- Create a new project (Description).
- Import one external package (Project/Import Package..).
- Go to Project in the left column, Presentation Tab, Installation Type.
- Add a Requirement "Result of an external script" for your core package. Point to any bash script.
- Do the same for imported package and point to the same script.
- Try to build the project.

Could someone please confirm the issue? This used to work with version 1.1.3.

Thanks,
Tom

**Comment by packagesdev** [comment]
Thanks for reporting this.

I can reproduce the issue and see where the problem lies. This will be fixed in version 1.2.1.

**Comment by misku** [comment]
Thanks for a quick response. What's the approximate 1.2.1 release horizon (days, weeks, months)? I'm just trying to find out whether creating a workaround makes sense ;-)

**Comment by packagesdev** [comment]
Before the end of the month. You can send me a message through the Hep > Send Feedback menu item so that I can notify you by mail when the most recent intermediary build for 1.2.1 contains the correction.

**Comment by misku** [comment]
Sounds great, thanks.

**Comment by packagesdev** [comment]
Problem fixed.

**Comment by misku** [comment]
That was quick. Thank you. I'm going to test it out tomorrow.

**Comment by misku** [comment]
I built Packages from the latest commit (9e09b400a4fd2e3b723047fc647de1b0177a7341), but problem still exists.
Here is a sample project: [https://wetransfer.com/downloads/e207680bce46ab1a59c8083214de0b5020171013135341/f0f3f203659962d30c88bee4f907e28520171013135341/4f3571](url)

**Comment by packagesdev** [comment]
It should have been read: problem fixed in the intermediate build.
