### ISSUE TITLE
Limitation in number of files/folders within a project?

### ISSUE THREAD

**Issue by joerg-eyring** [packagesdev/packages#105]
Hi,

our bundle contains ~25,000 files distributed over ~ 4,000 (sub)-folders. At a certain point building the package stops with an error similar to

![Bildschirmfoto 2021-11-16 um 15 21 58](https://user-images.githubusercontent.com/60919377/142002646-d3c8e6f8-ba4e-4219-807e-702a95a326ee.png)

We assume this error message is misleading since no file within this path contains extended attributes. We rather assume that at this point of building an internal limit of file/folder count is reached.

To prove this we deleted the directory in question and building the package stops at the next directory in the folder hierarchy. When deleting ALL subsequent files/folders in the hierarchy the build succeeds.

We'd appreciate getting a workaround or a bugfixed version.

Thanks and regards, Jörg

**Comment by packagesdev** [comment]
Hello,

I will try to reproduce that kind of issue.

In the meantime, maybe you can consider not disclosing the entire contents
of your .app bundle in the Payload hierarchy. If you're pretty happy with
the way it is by default, in 99.9% of cases, you just need to add the .app
bundle as is in the payload hierarchy. If you need to change the owner or
group, just do it for the .app item. The owner and group will be applied to
the enclosed filed without having to dsclosing the contents of the .app
bundle.

Accessorily, this should also speed the build process.

**Comment by joerg-eyring** [comment]
Hi,

thanks for your quick reply - and your suggestion works :-)

I didn't realize that "expanding" all items of a package has an impact on the build process - I did this to check if all owner and group attributes were set correctly.

Regards, Jörg

**Comment by packagesdev** [comment]
I am able to reproduce the issue in macOS BS but not in macOS Mojave. It's a bug in Apple's Frameworks.

I will add a workaround in the 1.2.10 release but feel free to report the issue to Apple.
