### ISSUE TITLE
Building a package

### ISSUE THREAD

**Issue by milkon-fishbrain** [packagesdev/packages#109]
Hey!
I'm trying to build a package but i'm getting this error message  "Unable to copy item at path '/Users/user/Documents/folder' because you don't have permission to create it inside the folder 'Applications'"

**Comment by packagesdev** [comment]
Full Disk Access needs to be granted to Packages. Check either the User Guide or this Q&A: http://s.sudre.free.fr/Software/Packages/Q&A_7.html
