### ISSUE TITLE
Select temporary folder already red

### ISSUE THREAD

**Issue by lolipale** [packagesdev/packages#11]
Hello,

Thank for the new update of Packages.
But I cannot build any packages on High Sierra 10.13.
I have an error with the build process. The process stop run with any message.
See the screenshot above
![copie d ecran 2017-10-16 a 16 40 27](https://user-images.githubusercontent.com/13834698/31617904-c42e5ab8-b290-11e7-82e9-b5a50611b2eb.png)

**Comment by packagesdev** [comment]
If you can send me the project file (just the project file) by mail, this would help.

Also, if there are additional logs in system.log.

**Comment by lolipale** [comment]
Hello,
This is the project file :
[config_system_10.12.6.adp.pkgproj.zip](https://github.com/packagesdev/packages/files/1394594/config_system_10.12.6.adp.pkgproj.zip)

I did not find anything in the logs but perhaps, I don't know

**Comment by packagesdev** [comment]
I can not reproduce the issue so far.

You mention "select temporary folder already red", are you referring to the build folder in the Settings pane or is it something else?

**Comment by lolipale** [comment]
I don't know why but the version 1.2.1 (233) fix my issue.
You can close this ticket.
Thank you a lot for your support and time !
