### ISSUE TITLE
Mixed GUI in darkmode on Monterey 12.2

### ISSUE THREAD

**Issue by Lotusshaney** [packagesdev/packages#110]
Not sure this is correct ?  Getting mixed Light/Dark modes on Monterey 12.2
![Screenshot 2022-02-07 at 16 11 15](https://user-images.githubusercontent.com/1845849/152827279-d66356bd-0c1f-4166-b238-a1d396bb4392.png)

**Comment by packagesdev** [comment]
I understand the origin of the issue with the source list.
For the fake window, this does not happen with earlier version of macOS. It could be that the name of the effective appearance is not the expected one.

**Comment by packagesdev** [comment]
OK, I see the origin of the issue for the fake window. This will be addressed in version 1.2.11.

**Comment by packagesdev** [comment]
In the meantime, you can probably use this hidden default to workaround the issue (which can occur on Big Sur and Monterey):

defaults write fr.whitebox.Packages ui.project.presentation.appearance-switch.show -bool YES

which will add an appearance switch in the Presentation pane. Not 100% convenient but better than nothing.

**Comment by packagesdev** [comment]
Fixed for 1.2.11.
