### ISSUE TITLE
Bug: build does not pass after updating from v.1.2.9 to v.1.2.10.

### ISSUE THREAD

**Issue by yuta-ishii-ts** [packagesdev/packages#111]
When I try to build a .pkgproj file created with v.1.2.9 with v.1.2.10 Packages, it fails with the following error.
![ss](https://user-images.githubusercontent.com/87348315/153344788-d729a013-0bfb-4fa0-9738-dc7cfa295b3a.png)

Is there a way to work around this problem?
If not, how can I download the installer for v.1.2.9?
From the web page, I can only download the latest version (v.1.2.10) or v.1.1.3.
I am very much in need of help and hope for a quick response.

**Comment by yuta-ishii-ts** [comment]
Thanks for your reply.

> This would require to know which value is set for the Identifier of the package. You can contact me at [dev.packages@gmail.com] if needed.

ok.
I' ll contact the gmail address later with the data attached.

> The URL for an older version looks like http://s.sudre.free.fr/Software/files/Packages_XYZ.dmg
So for 1.2.9:
http://s.sudre.free.fr/Software/files/Packages_129.dmg

Unfortunately, the dmg version of v.1.2.9 could not be downloaded.
I was able to download the v.1.2.8 one, so it seems to be a problem only with this version.
Could you please check?

**Comment by yuta-ishii-ts** [comment]
@packagesdev 
I confirmed that I can download the dmg of v.1.2.9. Thank you very much.
I have also sent the file that causes the problem to gmail. Please check it.

**Comment by packagesdev** [comment]
'_' character in identifier.
