### ISSUE TITLE
Packages not being identified correctly in MDM Provider

### ISSUE THREAD

**Issue by JoeIzzard** [packagesdev/packages#113]
Hello,

I'm new to Packages so may just be missing something simple.

I am using Packages to build .pkg files for use with our MDM provider, which pulls some information from the package to validate it. One of those bits of info is the Package name, which on official packages such as Google Chome is correct however with ones built in Packages in coming back as `DISTRIBUTION_TITLE`.

Is there a setting somewhere I am missing to set this correctly?

**Comment by rudyrichter** [comment]
See: https://github.com/packagesdev/packages/issues/69

**Comment by JoeIzzard** [comment]
So looking through that and extracting a .pkg, it seems that the MDM provider can't use the localisation strings in the Distribution file, is there any way to build without localisation strings and have the actual title in the Distribution file?

**Comment by packagesdev** [comment]
If your distribution title will not be localized, you can remove the default English localization and then the title will be in the Distribution file.

1. Select the Project row in the source list.
2. Click Presentation tab
3. Choose Title in the popupbutton of the inspector pane (ctrl + 0)
4. Select all the rows (cmd + A)
5. Click the '-' button.

**Comment by JoeIzzard** [comment]
Brilliant thank you! This fixes my problem perfectly!
