### ISSUE TITLE
Installation order of packages

### ISSUE THREAD

**Issue by d1ss0nanz** [packagesdev/packages#117]
How is the installation order determined if there's more than one package in a project?

I've 4 packages and I tried to order them by prefixing their names with "01, 02, 03, and 04". 
But the order of the pre- and postinstall scripts doesn't seem to follow the view order in the Packages UI.

How can I influence the preinstall, install, postinstall order of the packages?

**Comment by packagesdev** [comment]
The order of installation of the packages in a distribution is determined by the order of the choices (in the Project > Presentation > Installation Type pane).
