### ISSUE TITLE
Packages 1.2.1 crashes under macOS High Sierra 10.13 with Supplement Update

### ISSUE THREAD

**Issue by vfr** [packagesdev/packages#12]
After opening an existing Packages project and picking Build from the Build menu, Packages 1.2 (and 1.2.1) crash under macOS High Sierra 10.13 with Supplement Update. Please see [crash.txt](https://github.com/packagesdev/packages/files/1412785/crash.txt) log file.

**Comment by packagesdev** [comment]
Thanks for reporting this and for the crash log.

The problem has been fixed for 1.2.1.
