### ISSUE TITLE
Presentation pane does not display on Ventura GM

### ISSUE THREAD

**Issue by Lotusshaney** [packagesdev/packages#124]
When clicking on the Presentation pane, nothing changes other than the pane is highlighted.  It shows the contents of the pane you were last on.  As a result you cannot set any of the Presentation settings for a PKG.
![Screenshot 2022-10-26 at 15 46 09](https://user-images.githubusercontent.com/1845849/198058703-eaf3298f-8167-4c2f-ab5d-25de2c066548.png)

**Comment by packagesdev** [comment]
Hello,

this is a known issue that has been fixed in this commit:

https://github.com/packagesdev/packages/commit/9514830caf765f956f9b8ec8a7587a03f1e0f508

The fix is included in the intermediary, non-notarized build available here:

http://s.sudre.free.fr/files/Packages_1211_dev.dmg

**Comment by Lotusshaney** [comment]
Thanks this fixes the problem

**Comment by Lotusshaney** [comment]
Link works for me, just downloaded the dang without problem

**Comment by hanpo** [comment]
Thank you! , it can be downloaded through the curl command, but I can't download it with chrome.

**Comment by KaceyHaley-LG** [comment]
@hanpo when downloading via curl, the dmg i got was corrupt. what did you run exactly?

**Comment by AndyTitu** [comment]
I can download the 1.2.11 installer from http://s.sudre.free.fr/files/Packages_1211_dev.dmg but it actually installs Packages 1.2.10, so the issue is still there.

**Comment by packagesdev** [comment]
It does install version 1.2.11.

[image: Screenshot 2023-09-11 at 23.37.18.png]

**Comment by ferben** [comment]
> It does install version 1.2.11.

Sure but it contains Intel binaries only, not Universal (Intel+Apple Silicon).

**Comment by chinenual** [comment]
When I try to install 1.2.11 on my M2 MBP, I get an error when double clicking "Install Packages.pkg".   ("There is no application set to open the document "Install Packages.pkg" ") Is that because the binary is not universal? (can't run a pkg file via Rosetta?)

**Comment by ferben** [comment]
> When I try to install 1.2.11 on my M2 MBP, I get an error when double clicking "Install Packages.pkg". ("There is no application set to open the document "Install Packages.pkg" ") Is that because the binary is not universal? (can't run a pkg file via Rosetta?)

No.
You can try:
1. reboot or
2. assign pkg extension to Installer.app (/System/Library/CoreServices/Installer.app) manually or
3. try fix it by Onyx.app (clean caches)

**Comment by chinenual** [comment]
Thanks @ferben!    Reboot didn't help, but I was able to run the installer manually with "Choose Application...".   Perhaps obvious to others (but not to me), other .pkg files still open normally - this was the first time I've seen this happen.   

I can also confirm that onc I managed to install it, 1.2.11 properly displays the Presentation tab for my project.

**Comment by TaleTN** [comment]
FYI: I ran into this problem with Packages 1.2.10 on macOS Sonoma 14.4.1 (on an M1 Mac), and installing Packages 1.2.11 dev fixed the issue for me.

**Comment by laurentNoudohounsi** [comment]
I used on Apple M1 Pro running Sequoia 15.0 and so far it seems to work.
Do we have any information regarding the official release of the version 1.2.11? Is there something that block the distribution of this version?

**Comment by TaleTN** [comment]
Well, at my end I do have to reinstall Packages 1.2.11 dev after every macOS Sonoma update, but otherwise it indeed seems to work just fine.

**Comment by laurentNoudohounsi** [comment]
> Well, at my end I do have to reinstall Packages 1.2.11 dev after every macOS Sonoma update, but otherwise it indeed seems to work just fine.

Ok, good to know. I will see with the next updates then (and will keep a copy of the package dmg 🙂). 
Thanks
