### ISSUE TITLE
External resources

### ISSUE THREAD

**Issue by ngalkin** [packagesdev/packages#13]
Hello, 

Could you help me please. Is there any chance to check if the file exist than do not overwrite it. I tried to put some file to resources and write a post-install script. How can I get file path from script? 

Could I place file somewhere in payload and then copy it in right place when file is not existed. How can I get path for the file in post-install script? 

Thanks.

**Comment by packagesdev** [comment]
- The relative path to the contents of the Extra Resources is ./. So from the post-install script, you can write:

cp ./myfile /some/destination

- From your description, it looks like you are trying to install a file only during a clean installation.

Usually, there are 3 possible solutions:

- if you are installing both an application and some default files, the real solution is to have the application creates these files when they do not exist.

- you can use a post-installation script as you describe and copy the file from the extra resources:

if [ -f /some/known/location/myfile ]; then

   /bin/cp ./myfile /some/known/location/myfile

fi

- if you are installing other files in all cases, another solution is to use 2 separate packages withing a distribution project and to add a Files requirement to the choice that corresponds to the package installing the default file. The requirement settings should be:

  Any of the following files Must not Exist on Destination:

/some/known/location/myfile

When this requirement is not met:

Hide this choice.

Then you can set the User to see only the Standard Install.

**Comment by ngalkin** [comment]
Sorry for the delay. Thanks for the response. 
A small question what about home directory of user? There are many location in ~/Library. For now it's possible to make/copy/move/remove files from script. Can I make it via Payload. For example, I need to put file to ~/Library/Application\ Support/Mozila/NativeMessagingHost?

**Comment by packagesdev** [comment]
Check http://s.sudre.free.fr/Software/Packages/Q&A_3.html
