### ISSUE TITLE
packagesbuild command always report "less than a second" process time

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#14]
Terminal command packages build always report "less than a second" time.
"packagesbuild Installer: Build Successful (less than a second)"

It might be caused by wrong position?:
`_startTime=time(NULL);	// Necessarily state begin`
in PKGCommandlineBuildObserver.m

**Comment by packagesdev** [comment]
Yes, in non verbose mode, the time is incorrectly reported. This is due to the fact that there is a info event that is generated for the project. So _startTime=time(NULL); is called late during the build process.

**Comment by packagesdev** [comment]
Fixed in 1.2.2 (315)

**Comment by ferben** [comment]
Verified – Thank you :-)
