### ISSUE TITLE
Checksum changed on website download, but version info is same.

### ISSUE THREAD

**Issue by FiniteSingularity** [packagesdev/packages#144]
As far as I can tell, the last time Packages was updated was in Feb of 2022.  However, last night, the checksum of the Packages.dmg downloaded from your website: http://s.sudre.free.fr/Software/files/Packages.dmg changed, while the reported version remained v1.2.10. I was able to find a wayback machine snapshot from July, here: https://web.archive.org/web/20230727054218/http://s.sudre.free.fr/Software/files/Packages.dmg

Comparing this files shows slight different file sizes and checksums, but both report being v1.2.10:

```
~/Downloads 
❯ ls -la Packages-*.dmg 
-rw-r--r--@ 1 mark  staff  8398465 Sep 24 13:09 Packages-Current.dmg
-rw-r--r--@ 1 mark  staff  8398202 Sep 24 13:22 Packages-Wayback.dmg

~/Downloads 
❯ sha256sum Packages-*.dmg       
9d9a73a64317ea6697a380014d2e5c8c8188b59d5fb8ce8872e56cec06cd78e8  Packages-Current.dmg
6afdd25386295974dad8f078b8f1e41cabebd08e72d970bf92f707c7e48b16c9  Packages-Wayback.dmg
```

Combined with the fact that your website is still running without SSL, gives me some concern.  Can you please provide some info as to why there was a sudden change in file size and checksum with no documented/disclosed changes?

**Comment by packagesdev** [comment]
This change fixes the issue with macOS Ventura being dumb and unable to handle a double-click on a symbolic link in a disk image.

Basically, the Install Packages.pkg symbolic link on the disk image has been replaced by the original file which was in the hidden packages folder (so the package has not been rebuilt).

And the ReadMe on the disk image has been updated to take into account this change.

As a reminder, the disk image is not signed. It's the installation package and its payload that are signed and notarized (in 1.2.10).

If you prefer to use the old 1.2.10 disk image, it's available here:

http://s.sudre.free.fr/Software/files/Packages_1210_1.dmg
