### ISSUE TITLE
Distribution packages missing product id, necessary for startosinstall inclusion

### ISSUE THREAD

**Issue by poundbangbash** [packagesdev/packages#15]
Documented at https://managingosx.wordpress.com/2017/11/17/customized-high-sierra-install-issues-and-workarounds/ distribution-style packages need to have a unique product IDs included in the distribution file for it to work with `startosinstall`'s `--installpackage` option.  Without a product id the package is not included in the output of that tool.

This FR is to ask to include a product ID when building a distribution pkg.

Example:
Add `<product id="com.foo.bar.pkg" version="1.0"/>` to the distribution

```
<?xml version="1.0" encoding="utf-8"?>
<installer-gui-script minSpecVersion="1">
    <pkg-ref id="com.foo.bar.pkg">
        <bundle-version/>
    </pkg-ref>
    <options customize="never" require-scripts="false"/>
    <choices-outline>
        <line choice="default">
            <line choice="com.foo.bar.pkg"/>
        </line>
    </choices-outline>
    <choice id="default"/>
    <choice id="com.foo.bar.pkg" visible="false">
        <pkg-ref id="com.foo.bar.pkg"/>
    </choice>
    <pkg-ref id="com.foo.bar.pkg" version="1.0" onConclusion="none" installKBytes=“3">#FooBar.pkg</pkg-ref>
    <product id="com.foo.bar.pkg" version="1.0"/>
</installer-gui-script>
```

**Comment by packagesdev** [comment]
It's a feature supported in the Advanced Options for version 1.2.2. It's already integrated in the intermediate builds.

**Comment by poundbangbash** [comment]
Another passing thought on this.  It appears that Apple's own packages have the same value for `pkg-ref id` and `product id` (which makes me wonder why they need product id in the first place).  Could the Packages application default for distribution style pkgs be to include the `product id` automatically to match the `pkg-ref id` and use the GUI interface to override the default instead of having to opt-in to the `product id`?  

If not, could there be a preference to let the admin choose to have the `product id` match `pkg-ref id` by default?

**Comment by packagesdev** [comment]
I need to think about this.

**Comment by packagesdev** [comment]
product id and version supported in 1.2.2 (315).

**Comment by poundbangbash** [comment]
This can be closed as it is now incorporated in the product.  Appreciate it!
