### ISSUE TITLE
Permissions for children not inherited

### ISSUE THREAD

**Issue by k0nker** [packagesdev/packages#151]
I might be missing something, but I gathered from the documentation that children of a folder will inherit the permissions set for the parent. That doesn't seem to be working for a package I am building.

I went back to the .app and ran `chown -R root:wheel` and `chmod -R 755` on it and verified the permissions were all set. After adding it back to the Packages project, it set it to root:admin as the only user with permission to read or execute. I switched the .app back to the correct permissions then packaged it out. The package runs but then fails. The .app is placed in the correct spot, but the permissions are messed up. The .app retains the exec and read for everyone, but the Contents is set to system only as well as all sub folders.

If I manually expand every single folder in Packages and then highlight them all to set the permissions to root:wheel with read and exec on for all, it works.

Is there a way to force all children of the parent to inherit the parents permissions set in the Attributes pane without going file by file and expanding every folder? I have tried this with a brand new project and an existing project and it just doesn't seem to respect the permissions set to the parent nor can I see an option to apply all permissions to children.

**Comment by packagesdev** [comment]
If an item is visible in the Payload hierarchy, the user, group and POSIX permissions listed for that item in the hierarchy will be applied.
If you have a folder in the Payload hierarchy and its contents is not disclosed (that is the folder, bundle) is presented as if it was just item with no children, then the user and group of this item will be applied to all its children in the final payload. The POSIX permissions of the children will be the ones of the sources.

**Comment by k0nker** [comment]
Alright, so then with that information, if I need to modify a single file inside of a folder or bundle, I need to expand once, and just go that route slowly expanding once until I get down to what I need to modify and make the change on the specific file.

Along the way, anything that's exposed in the UI hierarchy structure I will need to manually make sure the permissions are set to what I expect them to be when packaged out.

Is that correct? Just making sure! Because if so that now makes complete sense and I was having a comprehension issue when checking the guide.

**Comment by packagesdev** [comment]
Yes. Or you could make sure that the POSIX permissions of this file are correctly set in the source. Whatever is more convenient for you.

**Comment by k0nker** [comment]
Thank you for the apt response and clarity. I appreciate all that you do for the community!
