### ISSUE TITLE
Change Install Location option is useless in some cases

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#18]
**How to reproduce:**
Open included testProj package file. Build and run installer. Go forward to section "Instalation type"

**Actual result:**
At Instalation type section appear button "Change Install Location…".
If you click on it you can see all connected disk but only startup disk can be selected.

**Expected result:**
There shouldn't be button "Change Install Location…" at Instalation type section –> it is useless because project has enabled option "Install on startup disk only", so you cannot change install location at alll.

**Additional info:**
I don't know if it is can be solved by Packages, or it is bug of Installer.app. On the other side this is really minor issue

[testProj.zip](https://github.com/packagesdev/packages/files/1541850/testProj.zip)

**Comment by packagesdev** [comment]
It's a very old bug (~ 8-year-old) in Installer.app.

Bug reports have been filed a long time ago and Apple has not fixed it.

You can file a new one on bugreporter but it's probably a waste of time.

**Comment by ferben** [comment]
I found solution.
If you let show Advanced options in Packages.app preferences and check option "domains->system volume" (see screenshot). The button "Change Install Location…" at last installer step disappear 👍 
<img width="1040" alt="screenshot" src="https://user-images.githubusercontent.com/5236788/34897552-d2237056-f7ee-11e7-93ce-2d1e8ac3d9be.png">
