### ISSUE TITLE
Multiple run external script issue

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#19]
**How to reproduce:**
Make installer package and run.

**Current behavior:**
Only 1st test show dialog.

**Expected behavior:**
There shoule be both dialogs displayed.

[Archiv.zip](https://github.com/packagesdev/packages/files/1578690/Archiv.zip)

**Comment by ferben** [comment]
```
	function installation_check()
	{
		var tResult;

		var tScriptArguments0=new Array();

		tResult=IC_CheckScriptReturnValue('1stTest.sh',tScriptArguments0,IC_COMPARATOR_IS_EQUAL,0);

		if (tResult==false)
		{
			my.result.title = system.localizedString('REQUIREMENT_FAILED_MESSAGE_INSTALLATION_CHECK_1');
			my.result.message = system.localizedString('REQUIREMENT_FAILED_DESCRIPTION_INSTALLATION_CHECK_1');
			my.result.type = 'Warn';
		}

		if (tResult==true)
		{
			var tScriptArguments1=new Array();

			tResult=IC_CheckScriptReturnValue('2ndTest.sh',tScriptArguments1,IC_COMPARATOR_IS_EQUAL,0);

			if (tResult==false)
			{
				my.result.title = system.localizedString('REQUIREMENT_FAILED_MESSAGE_INSTALLATION_CHECK_2');
				my.result.message = system.localizedString('REQUIREMENT_FAILED_DESCRIPTION_INSTALLATION_CHECK_2');
				my.result.type = 'Warn';
			}
		}

		return tResult;
	}
```

There is unexpected nesting:
```if (tResult==true)```

**Comment by packagesdev** [comment]
It's not possible to display 2 dialogs for the installation_check part.

See https://developer.apple.com/library/content/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW12

That's also the reason why potential 'Fatal' results are checked before the 'Warn' ones. 

Warning the users about 2 requirements A and B not being met would require you to write your own installation_check JavaScript function and define 3 potential localized error messages (one for A, one for B and one for A and B). This is not supported by Packages at this time.

**Comment by ferben** [comment]
Thank you for the explanation 👍

**Comment by ferben** [comment]
So there should be limitation for insert only one external script into Requirements (install-check part) in Packages, but understand it is a little complicated

**Comment by ferben** [comment]
I found soluton for two dialogs. Not so cool but working.

[Archiv2.zip](https://github.com/packagesdev/packages/files/1580991/Archiv2.zip)
