### ISSUE TITLE
Missing part of GUI? in Referenced Package UI

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#20]
Add Referenced package into Distribution Package. → see included screenshot.
It's cosmetic :-)

<img width="1312" alt="screenshot" src="https://user-images.githubusercontent.com/5236788/34897654-784977dc-f7ef-11e7-840e-e521c7d81ab6.png">

**Comment by packagesdev** [comment]
Thanks for reporting this. There are no missing parts. It's just that the padding is incorrect.

This will be fixed in 1.2.3

**Comment by packagesdev** [comment]
Fixed.
