### ISSUE TITLE
Packages not detecting Installed Developer Certificate. 

### ISSUE THREAD

**Issue by singhshashi** [packagesdev/packages#26]
I noticed this error in 1.2.1 and then in 1.2.3 when I upgraded. When I try to set the certificate for the project, Packages tells me "No Developer ID Installer Certificates could be found in your Keychain" 

![screen shot 2018-07-26 at 5 22 15 pm](https://user-images.githubusercontent.com/371601/43273824-1f51ba16-911b-11e8-9e00-cb3977eb87b8.png)

This is despite the fact that the Keychain does have a Certificate and Private Key. 

![screen shot 2018-07-26 at 9 31 42 pm](https://user-images.githubusercontent.com/371601/43274001-8ba88c44-911b-11e8-820f-0e24af91595d.png)

When I look at the Console for errors, I see the following: 

![screen shot 2018-07-26 at 8 22 50 pm](https://user-images.githubusercontent.com/371601/43274101-d06b4768-911b-11e8-8464-0718b5935a9e.png)

**Comment by rudyrichter** [comment]
That looks like an Application certificate, not a "Developer ID Installer" cert.

**Comment by singhshashi** [comment]
Thank you for pointing that out. I am new to Mac app development and was not aware that Installer certificate is separate. I now have it installed and working.
