### ISSUE TITLE
Remembering of previously installed packages

### ISSUE THREAD

**Issue by HP41** [packagesdev/packages#31]
This isn't an issue or could it be?

I've a package with multiple packages in it that the user can select to install or not.
What I've noticed is that once I've installed the package once on a machine, the next run shows an "Upgrade" instead of "Install" next to the option(s) that've been installed in the first run.
Just curious how this functionality is implemented and how I could tap into it for my custom install script/logic.

Thanks!

**Comment by packagesdev** [comment]
This is related to the receipt data base. You can use the pkgutil command line tool to access it.

You can check http://s.sudre.free.fr/Software/Packages/Q&A_5.html if you're trying to figure whether this is a first install or an update/upgrade.
