### ISSUE TITLE
Post-installation add a script,but the installation failed

### ISSUE THREAD

**Issue by jiagushuai** [packagesdev/packages#37]
screenshot as follows
+ create project
![image](https://user-images.githubusercontent.com/29997741/50430732-bd2cf180-0900-11e9-9136-31dcefeadc3b.png)
+ add scripts
![image](https://user-images.githubusercontent.com/29997741/50430833-4e9c6380-0901-11e9-8638-127b40c3984d.png)
+ build successful
![image](https://user-images.githubusercontent.com/29997741/50430849-67a51480-0901-11e9-866f-80bfdf3c5a80.png)
+ installtion fail
![image](https://user-images.githubusercontent.com/29997741/50430866-81465c00-0901-11e9-8ecf-2d4adb541d93.png)
+ start.sh
```
touch test.txt
```

**Comment by jiagushuai** [comment]
How should script files be written and used

**Comment by packagesdev** [comment]
Check the following document first. It may contain the answer:

http://s.sudre.free.fr/Stuff/Installer/Installation_Scripts/InstallationScripts-FAQ001.html

**Comment by jiagushuai** [comment]
After browsing the webpage, I modified the suffix as TXT and proofread the format. It ran successfully. Thank you very much!

**Comment by patchthecode** [comment]
Thank you this helped
