### ISSUE TITLE
Can the package do that automatically starts the script when it starts up？

### ISSUE THREAD

**Issue by jiagushuai** [packagesdev/packages#38]

**Comment by jiagushuai** [comment]
Support?
Or how should I implement it and look at those correlations

**Comment by jiagushuai** [comment]
Similar to this effect, automatically starts the script when Mac starts up
![image](https://user-images.githubusercontent.com/29997741/50876130-8aa5ed00-1406-11e9-936d-70da4c4ffa24.png)

**Comment by jiagushuai** [comment]
![image](https://user-images.githubusercontent.com/29997741/50877719-1f601900-140e-11e9-8862-0dc5e0054712.png)

**Comment by packagesdev** [comment]
If I understand correctly, you want to add an entry in the Login Items settings of the current user account.

This is possible. One solution is to write a little helper tool (see https://stackoverflow.com/questions/608963/register-as-login-item-with-cocoa) and call it from the post installation script of the package while making sure you are calling it as the current login user (see http://s.sudre.free.fr/Stuff/Installer/Installation_Scripts/InstallationScripts-FAQ001.html)

**Comment by jiagushuai** [comment]
Is this one way to get my program to boot up, or is there any other easy way

**Comment by packagesdev** [comment]
It won't start after the boot. It will start whenever a user logs in and run into this user's session.

**Comment by TheTechRobo** [comment]
Why did you close this ?
