### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by Lotusshaney** [packagesdev/packages#4]
Fresh clone of the repo

running build.sh and getting

ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)

any ideas what I can do ?

**Comment by packagesdev** [comment]
If the code is the one from 19 days ago, the build.sh script will fail anyway as the Xcode project for the main application is not in the repository yet (it will be).

Without knowing the version of Xcode and of the OS, I can't provide a diagnostic.

What I've seen on another machine (running OS X 10.8 and Xcode 5.1.1) I used build the project was that there probably should be a ./configure step for the xar submodule added to the build.sh script.

**Comment by ferben** [comment]
Hi,
I have the same issue. Xcode 8.3.3, SDK 10.12, macOS 10.12.6.

**Comment by packagesdev** [comment]
After further investigation, it's related to libcrypto not being included any more in recent SDKs. Since it's apparently not needed (the code uses the Apple Security and Crypto frameworks), the dependencies will be removed.
