### ISSUE TITLE
Cake tool for packagesbuild

### ISSUE THREAD

**Issue by awaescher** [packagesdev/packages#40]
I know packagesbuild as command line tool to build .pkg files from .pkgproj files. This is very handy on the developer machine but AFAIK requires Packages to be installed.
If you run your builds and deployments on a build host, you need to have it installed over there, too to use packagesbuild.

This is possible for own build hosts but gets difficult or impossible on services like Azure Pipelines or AppVeyor for example.

A great solution to avoid preinstalled build hosts I use very often is [Cake](https://cakebuild.net/).
It's a cross platform build (and more) scripting environment. The great thing about it is, that you can define dependencies as nuget packages in your build scripts. As soon as a Cake script is executed, it immediately restores all dependencies from nuget.org or other sources.
With that, you can make sure that your build script will work on each and every build host - no matter which software is preinstalled or not.

That was a long foreword, sorry. **I saw that there's no Cake tool for Packages yet so I'd like to offer to create and maintain one if you (the creators) accept that.**

### What does that mean?
I would make a Cake tool nuget package containing all the binaries required to run packagesbuild on a naked (macOS) build host. Only the command line tool, not the whole Packages bundle. In addition, I'd code a plugin for Cake exposing the methods to access the functionality of packagesbuild in C# code.

**With that, developers could install Packages to use it on their development machines, create their .pkgproj files, commit them to their repo and have it built on any naked build host later on.** 

On the build host, Cake would download the nuget package for packagesbuild containing all the binaries to run packagesbuild and invoke it to build the .pkg file.

### My Question
Would you be okay with that? Of course, I'd give all the credits to the creators (however, my name would be listed with the package on nuget.org as well).

### Foot notes
Cake is a very popular tool and its popularity is raising quickly. There are a lot of [tools](https://cakebuild.net/dsl/) and [add-ins](https://cakebuild.net/addins/) today. 

One I think is very close to the one I'd like to create is [NSIS for Cake](https://cakebuild.net/dsl/nsis/). It takes setup definition scripts for the Nullsoft Installation System and compiles them with a command line tool from Nullsoft. Exactly the same setting as I want to have for Packages, but only for Windows.

**Comment by awaescher** [comment]
That's cool, thanks.

I tried to put `packagesbuild`, `packagesutil`, `goldin`, `packages_build`, `packages_dispatcher` (from `PriviledgedHelperTools`) into a folder but that did not work. That was just a simple approach in my lunch break - so yes, I would be very happy if you could list me the requirements.

**Comment by packagesdev** [comment]
You will also need:
- the Locators and Requirements folders in /Library/PrivilegedHelperTools/fr.whitebox.packages . They contain converter plugins that are used by packages_builder.
- the fr.whitebox.packages.build.dispatcher.plist launchd plist file in the /Library/LaunchDaemons/ folders.

The packagesbuild command line tool can be moved around but the goldin, packages_builder and packages_dispatcher tools and Locators and Requirements are expected to be found in the locations defined in the Packages installation package (i.e. respectively /usr/local/bin and /Library/PrivilegedHelperTools/ helper. Idem for the launchd plist file.

Other locations can be defined but you would then need to modify the paths in the code.

**Comment by awaescher** [comment]
> but the goldin, packages_builder and packages_dispatcher tools and Locators and Requirements are expected to be found in the locations defined in the Packages installation package

Oh, with that, it is not possible to be used with Cake. Cake restores all its tools and add-ins to a /tools subfolder from where the Cake build script is located. I don't think that it is possible to write to /usr/local/bin for example. This way, the Cake tool would work like an installer and should provide possibilities to get uninstalled again.

Would you say it is a big change to modify the paths in the code or implement a fallback probing machanism scanning the local path for the requested files if the expected paths you mentioned are not available?

**Comment by packagesdev** [comment]
There could be some fallbacks implemented but I'm not sure this would be enough.

Is it possible to have launchd daemons in this environment? The communications during the build process is done via privileged XPCs.

**Comment by awaescher** [comment]
I'm not that deep into Cake but I'd say no: because launchd deamons won't work on Windows and Cake is cross-platform by design.
By default, the tools are downloaded to a subfolder of the Cake script and invoked from there. It's all plain .NET, so having assemblies (*.dll or *.exe) there is enough to load them in runtime and invoke methods from there.
However, it's no necessity that a Cake tool has to be written in .NET, because Cake can start processes as well (of course). And that's what I wanted to do: Write a Cake tool which then builds the command line for packagesbuild and invoke it then. As soon as it is invoked, packagesbuild can load each reference it wants to load - however, that Cake tool installation process can just deploy files and folders to the subfolder of the Cake script. So we need to have a packagesbuild which can load all its references from its working directory or subfolders of it.

**Comment by rudyrichter** [comment]
I don't think that would work at all, as a lot of what packages does needs privileges beyond the signed in user, thus `/Library/PrivilegedHelperTools/fr.whitebox.packages` its a semi-blessed directory for such tools to live.

**Comment by awaescher** [comment]
I agree, @rudyrichter. I'm very thankful, @packagesdev, for the time you took to spin your head around that issue. In this case - as sad as it is - I'm willing to close that issue. 

With this, packages has to be installed to the build hosts in future. However, if you have the control over your build host, you can still compile pkg files with Cake with packages by using ..

```
Task("CompileSetup")
    .IsDependentOn("Publish")
    .Does(() => 
{	
    // update the pkgproj file and run packagesbuild
    ReplaceRegexInFiles("_setup/RepoZ.pkgproj", "{PRODUCT_VERSION}", _appVersion);
    StartProcess("packagesbuild", "--verbose _setup/RepoZ.pkgproj");
});
```

That's what I do [here in the Cake build script of RepoZ](https://github.com/awaescher/RepoZ/blob/1736bc12d1ac71129a6c74ba5c124aecd3a86ab6/build.cake#L134).

#### For anyone thinking "What the hell did he want to do if that already works in RepoZ?"

Calling `StartProcess("packagesbuild")` will only work if packages is installed on the build host. If not, it will fail. Cake has an intelligent tooling mechanism which works by deploying required tools on the fly as soon as they are needed. However, we found out, that this kind of xcopy-deployment of packagesbuild won't work. So if you have no control over your build hosts (like when using Azure Pipelines), you cannot use packages because there's no way to preinstall it.
