### ISSUE TITLE
Access language selection

### ISSUE THREAD

**Issue by smariussorin** [packagesdev/packages#44]
Hi guys,

I`m using this great tool and I was wondering how can I get the language selection after installation or during selection?

Thanks

**Comment by packagesdev** [comment]
What is the "language selection" in this case?

**Comment by packagesdev** [comment]
Without any additional info, this can not be investigated.

**Comment by m0ve1337** [comment]
I also want to change the language of the application (i.e. Packages) --> mine is set to french and i don't see any option to change the GUI-language anywhere: would be nice if you could tell us, how to change the language

**Comment by packagesdev** [comment]
https://apple.stackexchange.com/questions/245/is-it-possible-to-launch-a-program-in-a-specific-language

Is this what you are trying to do?

**Comment by m0ve1337** [comment]
Exactly, thank you very much!
