### ISSUE TITLE
Enforced Sequence

### ISSUE THREAD

**Issue by cybik** [packagesdev/packages#46]
Is there any way to be *absolutely sure* that, in the case of Packages (this app) defining multiple packages&payloads, one specific payload is processed and installed before another? An absolute, enforced sequencing of install tasks, if you will

If it's already doing that, forget I even asked.

**Comment by cybik** [comment]
Cancel that, I was using your tool wrong.

**Comment by packagesdev** [comment]
Just in case, the order of installation is "defined" in the Project > Presentation > Installation Type pane.

The packages/payloads/choices are installed in the order defined in this list.
