### ISSUE TITLE
Installing a package as "Current User"

### ISSUE THREAD

**Issue by cybik** [packagesdev/packages#47]
Right now, I seem to be able to set the "Owner" of a target set of files (or file) to install anywhere, only to existing users on the development machine.

Is it possible to have an "Owner" entry that would be autodetecting which user is installing a given (set of) file(s) and set the installed file(s)' owner to that?

**Comment by packagesdev** [comment]
Check this document: http://s.sudre.free.fr/Software/Packages/Q&A_3.html
