### ISSUE TITLE
Unable to find signing certificate

### ISSUE THREAD

**Issue by DeysonOrtiz** [packagesdev/packages#51]
Hello and good day.
I have a valid Developer ID Installer and when I add the certificate and then build I get this error: 

<img width="332" alt="Screen Shot 2019-07-18 at 2 37 01 PM" src="https://user-images.githubusercontent.com/6247217/61483079-137b8380-a96a-11e9-874c-74eae4a4dfdb.png">

Please let me know what I may be doing wrong.  Thank you and have an amazing day!

**Comment by DeysonOrtiz** [comment]
It seems that my private key was not attached to the certificate.  Quick fix was to export Account Profile inside Xcode and then re-import it.

**Comment by packagesdev** [comment]
Interesting. This is an error case I try to address in a more human friendly way (with a more specific log description). I guess I will have to try to reproduce this scenario to better report it.
