### ISSUE TITLE
Building packages fails under macOS 10.15 beta

### ISSUE THREAD

**Issue by mthielemann** [packagesdev/packages#52]
Building a package under macOS 10.15 fails with error: "Incorrect type for file at path 'path to project.pkgproj'." Just wanted to let you know.

Regards,
Marc

**Comment by csteelatgburg** [comment]
Confirmed on 10.15 Beta (19A512f).

**Comment by packagesdev** [comment]
Just an idea as I haven't tried to reproduce the issue on macOS Cata. It could be possible that this is related to the new security measures that requires the user to allow a process to access the contents of the ~/Documents folder.

So 2 possible workarounds worth checking:

- moving the project to a location that's not impacted by Apple's annoying security user experience. e.g. /Users/Shared/

- granting Full Disk Access to /Library/PrivilegedHelperTools/fr.whitebox.packages/packages_builder

**Comment by mthielemann** [comment]
Granting Full Disk Access to /Library/PrivilegedHelperTools/fr.whitebox.packages/packages_builder did not change anything.

**Comment by packagesdev** [comment]
I did some tests with macOS Cata b5 and you also need to grant full disk access to /Library/PrivilegedHelperTools/fr.whitebox.packages/packages_dispatcher to make it work. This is a bit strange (and annoying) since this tool does not read any document on disk, it just launches packages_builder.

**Comment by mthielemann** [comment]
Just want to confirm that granting full disk access to packages_builder AND packages_dispatcher makes it work.

**Comment by cybertunnel** [comment]
Would it be possible for Packages to prompt those to be added?
