### ISSUE TITLE
in Catalina is not possible update files in System folders

### ISSUE THREAD

**Issue by grafikartes** [packagesdev/packages#56]
I had no problems with previous versions, but with Catalina is not possible up Systema files, we can add files but not modify, such as an icons. calro I tried with SIP disabled and running "sudo mount -uw /" script.

**Comment by packagesdev** [comment]
On all macOS versions where SIP is enabled, you can not modify anything in /System.

On macOS Catalina, you probably can not modify anything in /System because the system components are on a specific volume that is read-only even when SIP is disabled.

Ref. https://support.apple.com/en-us/HT210650
