### ISSUE TITLE
Cannot access to website

### ISSUE THREAD

**Issue by kriefsacha** [packagesdev/packages#59]
Hi,

I wanted to install this project which looks very useful but when i go to the website (http://s.sudre.free.fr/Software/Packages/about.html) it's not working.

Can you tell me what's happening ? Thanks.

![image](https://user-images.githubusercontent.com/35034421/69913349-69475880-143f-11ea-8e0d-ace7c14dc0a2.png)

**Comment by rudyrichter** [comment]
It seems to be working for me, just now.

**Comment by kriefsacha** [comment]
I have downloaded it from another source. Now i have another problem but i will open another ticket
