### ISSUE TITLE
Installing signed application issue

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#62]
Hello,
I have a issue when I install signed application a little bit complex app.
I manage signing manually using macOS codesign utility.
So when I place signed application bundle (I do signature verification) to Packages.app and created installer break signature of my application :-(

Reason:
See Apple's TN: https://developer.apple.com/library/archive/technotes/tn2206/_index.html
`To see why, it's necessary to understand that code signing uses extended attributes to store signatures in non-Mach-O executables such as script files. If the extended attributes are lost then the program's signature will be broken. Many file transfer techniques do not preserve extended attributes, nor are they preserved when uploading to the Mac App Store.`

System utility ditto in Packages use `--noextattr` by default.
Location: PKGProjectBuilder.m:5105 tTask.arguments=@[@"--noextattr",

Solution:
Remove option `--noextattr` ditto or make it's usage optionall.
Optionality can be implemented by checkbox in GUI or by automatic codesign detection (a little bit dificult) eg: launch `codesign -d -v .../*.app` and ensure if application bundle is signed or not.

**Comment by packagesdev** [comment]
See https://github.com/packagesdev/packages/issues/30

With Advanced options enabled, there is a "Preserve extended attributes" checkbox in the Payload > Settings pane.
