### ISSUE TITLE
Using CLI to change bundle identifier always results in Low Memory error

### ISSUE THREAD

**Issue by v-sypayr** [packagesdev/packages#63]
## Issue: 
When using the CLI to change the identifier of a particular bundle using the command 
`packagesutil --file <pkgproj path> set package-<index> identifier <string>`
any valid string returns the error `"packagesutil: Low memory"`

Examples of strings tested include `defaultIdentifier` and `com.mypackage.pkg.application`, in the format `packagesutil --file <pkgproj path> set package-1 identifier defaultIdentifier`.  These are valid identifiers when using the GUI to save the pkgproj, but do not work from the CLI using the above command.

## Possible Cause:
The pertinent line in [PUUtilities.m](https://github.com/packagesdev/packages/blob/b195cf8b69f6facf35c2db3572aa423bc1f11165/packagesutil/packagesutil/PUUtilities.m#L450) may have a bug. Please see
https://github.com/packagesdev/packages/blob/b195cf8b69f6facf35c2db3572aa423bc1f11165/packagesutil/packagesutil/PUUtilities.m#L450-L454 This is where the "packagesutil: Low memory" error arises. 

## Possible Solution:
It seems that `if (tFormatter!=nil)` may need to be `if (tFormatter==nil)` instead. When [PKGBundleIdentifierFormatter](https://github.com/packagesdev/packages/blob/b195cf8b69f6facf35c2db3572aa423bc1f11165/shared/PKGBundleIdentifierFormatter.m) initializes, it stores `NSCharacterSet * _forbiddenCharacterSet;`. It may be that if packagesutil is truly out of memory and PKGBundleIdentifierFormatter was not able to initialize properly, then the stored value will be nil. In this case, a properly initialized PKGBundleIdentifierFormatter would always trigger the error condition, which seems consistent with current symptoms.

## Request:
Would it be possible to check this issue, or otherwise resolve why the CLI can't be used to rename bundle identifiers? This is a very useful functionality for automating packaging workflows with Packages.

Thank you for your help!

**Comment by rudyrichter** [comment]
yeah, it looks like tFormatter==nil would be the right early return there.

**Comment by packagesdev** [comment]
You're right. Will be fixed in the next minor update.

**Comment by packagesdev** [comment]
Fixed in 1.2.9.
