### ISSUE TITLE
Packages itself not notarised: still running fine. How?

### ISSUE THREAD

**Issue by jvanakker** [packagesdev/packages#66]
How come, that if Packages itself was not notarized, it installed AND runs fine on this machine with macOS Catalina 10.15.3?
In the "Read Before You Install Packages.rtf" it contains a list of instructions to install on Catalina, which I clearly did not do, I just installed it the normal way, through double clicking/running the installer PKG and nothing else. It installed and runs fine without complaining. How is this possible?

I'm asking this because if it's not strictly needed to notarize, than it saves us the hassle of notarising our next release. I thought notarization was required after February 3, according to this Apple [news release](https://developer.apple.com/news/?id=12232019a).
Signing the PKG distribution is something we already did before, with our payed apple developer account certificate, but just not notarizing.

Sources:
http://s.sudre.free.fr/Software/Packages/Q&A_7.html

> At the time of this writing, I don't have any plan to notarize the Packages application itself (or its installation package, or its disk image).
> 
> I despise the fact that it's now required to pay $99 each year to distribute even freeware on the macOS platform. I'm fine about paying $99 every 5 years to get Developer ID certificates. I am not about paying that amount each year for no good reasons.
> 
> To install Packages on a macOS Catalina system, you will need to follow longer instructions than on previous macOS versions. Check the "Read Before You Install Packages" document at the root of the disk image.

**Comment by packagesdev** [comment]
As it's possible for anyone with a non expired Apple developer account to notarize it, it's not entirely impossible that someone did it.

Other possibilities involves the quarantine flag not being set somehow IIRC.
