### ISSUE TITLE
Multiple Installer Plug-in not working in Mojave

### ISSUE THREAD

**Issue by dgrech84** [packagesdev/packages#67]
I am creating two installer plugins using Xcode 11.4 and adding them to a package using Packages 1.2.8 with Catalina OSx.  What is happening is the the first plugin works perfectly but when going to the next one the the plugin callbacks are not called and furthermore the Pane Title will be the same as the first plugin. I also tried to swap the order of the plugins and same scenario happened, the first one works but the second fails.  

Note that this was also reproduced with Xcode 10.2 and Packages 1.2.8 under Mojave.

Can you please guide me on what I can do to solve this issue? 

I created a small demo to illustrate the above. If I swap Panel3 and test, the textfield string value will not be set to "HELLO" because didEnterPane was not called.  
[Screen Recording 2020-04-08 at 09.50.17.zip](https://github.com/packagesdev/packages/files/4449064/Screen.Recording.2020-04-08.at.09.50.17.zip)

**Comment by packagesdev** [comment]
Things that are worth checking:
- the class names of the subclasses of InstallerPane or InstallerSection are not the same in both plugins.
- the Info.plist files are correctly set.
- the InfoPList.strings file are correctly set.
- there are no exceptions in system.log.

**Comment by dgrech84** [comment]
Thanks for your prompt reply.

- changed the class names of the subclasses still didn't work

- The info.plist & info-list.strings are correct as I have created new plugins to test again

- there are no exceptions in systems.log

Note that the same pkg works in Catalina, but not in Mojave.

**Comment by packagesdev** [comment]
Can you send the built distribution to dev.packages@gmail.com so that I can try to reproduce this and figure out where the problem might be?

**Comment by dgrech84** [comment]
I managed to replicate with two clean plugins created within XCode. I went around the problem using your multiple pane solution.
