### ISSUE TITLE
Intune metadata

### ISSUE THREAD

**Issue by MichaelLambert78** [packagesdev/packages#69]
Running into an issue where packages deployed with Intune are not reporting back successful installation status once completed. Looks like Intune requires a couple of pieces that are not being added by default; CFBundleVersion and install-location. Had a ticket open with Microsoft on this but they were unable to help other than to just reitterate that it needs those 2 flags. I believe the CFBundleVersion can be included via the info.plist file. Attached the help article for this for reference. It's possible I'm missing a step, but looking for help on this.

https://support.microsoft.com/en-my/help/4344141/macos-lob-apps-aren-t-deployed-in-microsoft-intune

**Comment by rudyrichter** [comment]
@packagesdev any way to figure out where they're expecting CFBundleVersion to be supplied? at the pkg-info level?

**Comment by packagesdev** [comment]
> Running into an issue where packages deployed with Intune are not reporting back successful installation status once completed. Looks like Intune requires a couple of pieces that are not being added by default; CFBundleVersion and install-location. Had a ticket open with Microsoft on this but they were unable to help other than to just reitterate that it needs those 2 flags. I believe the CFBundleVersion can be included via the info.plist file. Attached the help article for this for reference. It's possible I'm missing a step, but looking for help on this.
> 
> https://support.microsoft.com/en-my/help/4344141/macos-lob-apps-aren-t-deployed-in-microsoft-intune

The version and install-location attributes are set for each .pkg.
The CFBundleVersion is listed when it's defined in the bundle Info.plist file.

There's something incorrect in the Microsoft document if they believe that the identifier of a package has to be the same as the bundle identifier of the application in the payload. There are 2 different identifiers which can be the same but don't have to be the same.
