### ISSUE TITLE
Plugin's Locale value is abnormal in Catalina OSX.

### ISSUE THREAD

**Issue by RuVnel** [packagesdev/packages#70]
I am creating two installer plugins using Xcode 11.3.1 and adding them to a package using Packages 1.2.9 with Catalina OSX.

when I ran this pkg file on Catalina OSX,
My Installer plugins in the Packages didn't apply normally localized string.

But I ran pkg file on under Catalina OSX ( ~ Mojave OSX),
My Installer plugins in the Packages apply normally localized string.

The file was the same and the only difference was macOS that was executed.

I'm using this source to getting locale information.
`[[NSLocale autoupdatingCurrentLocale] objectForKey:NSLocaleLanguageCode]; `
but it always return 'en' in my plugin on Catalina OSX.

How can I fix it ?

**Comment by packagesdev** [comment]
This looks more an issue in Installer.app.

So possible solutions include:
- reporting the issue to Apple using the Feedback Assistant.
- asking about this in the Apple Developer Forum
- use an Apple DTS incident.
