### ISSUE TITLE
Custom plugins are not displayed if run installer on macOS Big Sur

### ISSUE THREAD

**Issue by MaxSavkin** [packagesdev/packages#74]
Hi!
My installer doesn't show custom plugins when i run installer on Big Sur. In Catalina and or in earlier os x versions everything is fine. 
I tried to create new empty packages project and new installer plugin in XCode. But doesn't work either.
I'm not 100 percent sure that is a packages problem. If no, can anyone help me to fix it? Maybe someone could point me a direction to look on?
Thanks in advance.

![Screen Shot 2020-07-29 at 11 57 42 PM](https://user-images.githubusercontent.com/7190378/88895877-bb9c7b80-d251-11ea-88b8-1766f1578426.png)

**Comment by rudyrichter** [comment]
@MaxSavkin.

I don't know with any authority on this, but I think they've ceased support for installer plugins in Big Sur's Installer.app

**Comment by MaxSavkin** [comment]
It was problem of macOS. After upgrade to Big Sur Beta 4 the problem is gone
