### ISSUE TITLE
How to access distribution.xml before build in Packages?

### ISSUE THREAD

**Issue by Akash1604** [packagesdev/packages#75]
As i want remove "Introduction","Installation Type" and "Destination select" steps from installer. Because i want to avoid number of clicks on the installer UI.

**Comment by packagesdev** [comment]
I don't see how accessing the distribution.xml file would allow you to prevent these steps from being displayed.

They are always displayed. At best, the "Destination select" step will be skipped if Installer.app is not drunk and takes into account that you have set the destination to be the startup volume. But that's all that can be done AFAIK.
