### ISSUE TITLE
There are no pop-up boxes on the MacOS Big Sur that need to be restarted

### ISSUE THREAD

**Issue by Carelost** [packagesdev/packages#77]
On the MacOS Big Sur, we use packages to do the install, but there are NO pop-up boxes on the MacOS Big Sur that need to be restarted(The box should be :"When this software finishes installing, you must restart your computer. Are you sure you want to install the software now?").
In addition, also on the MacOS Big Sur, clicking the Install button will sometimes bring up two pop-ups for permissions. The first access box closes, followed by the second. And the Install button can be clicked repeatedly, if you click cancel, it will continue to generate new access window.
Have you ever had this issues? 
Looking forward to your reply, Thank you!

**Comment by packagesdev** [comment]
Looks like a bug in the betas of Installer.app.
