### ISSUE TITLE
Question: Will InstallerPlugin (x86_64 binary) work on ARM macs

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#80]
Hello,
I'm sorry for trivial question.
I have installer with InstallerPlugin (x86_64 binary), will it work on ARM (M1) macs with no issue?
Rosetta 2 should handle it but I cannot prove it on real machine?

Thank you

+FE

**Comment by rudyrichter** [comment]
It relaunches Installer.app under rosetta to run it with your plugin, and any scripts are run under rosetta as well.

**Comment by ferben** [comment]
Thank you a lot 👍
