### ISSUE TITLE
Not working in BigSur

### ISSUE THREAD

**Issue by samratsm** [packagesdev/packages#85]
I'm trying to build in BigSur. I've added a shell script for postinstallation stage but I'm getting following message:

![image](https://user-images.githubusercontent.com/69664558/108324577-185f8380-71ee-11eb-857b-c9c3ca6a5a55.png)

![image](https://user-images.githubusercontent.com/69664558/108324701-3c22c980-71ee-11eb-9e56-de164fd19166.png)

**Comment by packagesdev** [comment]
This looks like a Full Disk Access issue. See http://s.sudre.free.fr/Software/Packages/Q&A_7.html
