### ISSUE TITLE
How can I add files to /usr/local/bin?

### ISSUE THREAD

**Issue by hdwyx** [packagesdev/packages#86]
When I set the payload to be in /usr/local/bin then build it, it says "Unable to copy item at path 'FILE' because you don't have permission to create it inside the folder 'bin'".
How can I fix this?

**Comment by TheTechRobo** [comment]
Say "requires admin/root priveleges" or similar

**Comment by sertdfyguhi** [comment]
No it does not

**Comment by sertdfyguhi** [comment]
don't know where it is

**Comment by sertdfyguhi** [comment]
also if i tick "require admin password for installation" it doesnt work too

**Comment by sertdfyguhi** [comment]
and i also have permissions to write in /usr/local/bin

**Comment by TheTechRobo** [comment]
> and i also have permissions to write in /usr/local/bin

That can get pretty dangerous. If you use it for homebrew, I suggest giving those privileges to a user never logged into except with "su" for brew, for security reasons.

**Comment by TheTechRobo** [comment]
shit i just realised, SIP will not

**Comment by packagesdev** [comment]
It should be possible to add files to /usr/local/bin because this is what I do for the Packages installation package itself.

See https://github.com/packagesdev/packages/blob/master/distribution/Packages.pkgproj

**Comment by TheTechRobo** [comment]
Maybe this is the reason that people get no response when building - maybe the packages binary isn't there after install.

I don't know - correct me if I'm wrong - but this seems plausible.

**Comment by hdwyx** [comment]
> It should be possible to add files to /usr/local/bin because this is what I do for the Packages installation package itself.
> 
> See https://github.com/packagesdev/packages/blob/master/distribution/Packages.pkgproj

The issue is, it doesn't work

**Comment by hdwyx** [comment]
if i set group to 'wheel', it says 'Unable to read extended attributes of item at path 'PATH TO FILE''

**Comment by packagesdev** [comment]
Does the error occur when you build the package or when you install the package?

If it occurs when you build the package, this may be a Full Disk Acces (FDA) issue.

See http://s.sudre.free.fr/Software/Packages/Q&A_7.html

**Comment by hdwyx** [comment]
Thanks! It finally worked.
