### ISSUE TITLE
Proposal: Make a clear, distinct option for Apple Silicon support (affects scripts only)

### ISSUE THREAD

**Issue by andre4ik3** [packagesdev/packages#87]
On Apple Silicon Macs, all scripts in all packages **will** be ran under Rosetta 2, unless the package specifically declares that it's compatible with Apple Silicon.

It does this with this key inside of the Distribution file:
`<options hostArchitectures="x86_64,arm64"/>`

Right now, I manually add this to my packages I build. It would be great if there was an option to automatically embed this, maybe with a toggle.

**Comment by rudyrichter** [comment]
you can also turn on 'show advanced user options' on the advanced tab of prefs to get the main package UI to show the options section to add hostArchitectures directly into the pkgproj (unclear if you were modifying the Distribution file post-build or not).

agreed it would be nice if this was a checkbox and/or a toggleable value based on the command line utility's options for adjusting the package project at build time.

**Comment by andre4ik3** [comment]
Ah. Didn't see that, thanks.

I still think it would be important to add a switch that's easier to access and / or put Apple Silicon support on by default (it only affects pre-post install scripts)

**Comment by scritturamista** [comment]
> you can also turn on 'show advanced user options' on the advanced tab of prefs to get the main package UI to show the options section to add hostArchitectures directly into the pkgproj (unclear if you were modifying the Distribution file post-build or not).

Sorry for dropping in on this conversation... just stumbled on this and would like to remove Rosetta dependency from my installers. After you’ve enabled Show Advanced User Options, where exactly would you go and enter <options hostArchitectures="x86_64,arm64"/>?

**Comment by packagesdev** [comment]
In the 1.2.10 version, the hostArchitectures is automatically computed (unless a value was set manually).

**Comment by scritturamista** [comment]
> In the 1.2.10 version, the hostArchitectures is automatically computed (unless a value was set manually).

That sounds excellent :-) How does it know which hostArchitectures to populate automatically? (I'm thinking of a mix of binaries, for example, some fat, some Intel-only, some ARM-only, for example).

**Comment by packagesdev** [comment]
It checks the architectures of each binary in the payloads and the additional resources. And it finds the intersection of the supported architectures by all binaries.

So if you have some FAT, some Intel-only and some ARM-only binaries, the hostArchitectures value will not be set. Because the algorithm can not figure out the following things:
- a binary will not be installed on some platforms.
- a binary will not be run on some platforms.

So in your example, you will need to set the hostArchitectures option manually in the project.
