### ISSUE TITLE
Add arm64 support

### ISSUE THREAD

**Issue by Coros** [packagesdev/packages#97]
I'm unable to check for CPU requirements since Packages does not recognize arm64 as a valid CPU type.  I tried creating a script that would check for me, but I've found that won't work because arm64 is not listed in the distribution xml so it relaunches the installer with rosetta and the check fails due to that.

**Comment by Coros** [comment]
Looking through your commits, it appears this may already be resolved.  Will a new version be published soon?

**Comment by Coros** [comment]
duplicate issue anyway

**Comment by packagesdev** [comment]
If you are a thrill seeker, there is a development build that does this automatically in most cases:

http://s.sudre.free.fr/files/Packages.dmg

It's also a notarized universal build.
