### ISSUE TITLE
arm64 support (opening a .pkg file on M1 Mac result in prompt to install Rosetta 2)

### ISSUE THREAD

**Issue by PatrickKunz** [packagesdev/packages#99]
I need a way to add arm64 to the installer arch requirements additional to x64. Otherwise, silicon M1 users with the latest macOS will be prompted to install rosetta. 

See here:
https://developer.apple.com/forums/thread/667672

**Comment by PatrickKunz** [comment]
Any help on this one would be great. It is a show-stopper for us. 

Is there a workaround for this?

**Comment by delize** [comment]
Also running into the issue here... 

Will re-tool towards CLI based commands going forward. :(

**Comment by delize** [comment]
@PatrickKunz 

Thanks to [@kevinmcox](https://github.com/kevinmcox) & [@scriptingosx ](https://github.com/scriptingosx), they mentioned/specified this:

https://scriptingosx.com/2020/12/platform-support-in-macos-installer-packages-pkg/
http://s.sudre.free.fr/Software/documentation/Packages/en_2017/Project_Configuration.html

Once enabled, enter the following: `arm64,x86_64`

**Comment by PatrickKunz** [comment]
> @PatrickKunz
> 
> Thanks to [@kevinmcox](https://github.com/kevinmcox) & [@scriptingosx ](https://github.com/scriptingosx), they mentioned/specified this:
> 
> https://scriptingosx.com/2020/12/platform-support-in-macos-installer-packages-pkg/
> http://s.sudre.free.fr/Software/documentation/Packages/en_2017/Project_Configuration.html
> 
> Once enabled, enter the following: `arm64,x86_64`

Thanks a lot for the info. I was able to do that. Just have to wait for user feedback.

**Comment by PatrickKunz** [comment]
I can confirm that this worked. You can see that the installer is executing as apple process on M1 machines after adding those settings.

**Comment by packagesdev** [comment]
If you are a thrill seeker, there is a development build that does this automatically in most cases:

http://s.sudre.free.fr/files/Packages.dmg

It's also a notarized universal build.
